export const CHAT_DOCUMENT_ATTRIBUTE = "CHAT_DOCUMENT"
export const CHAT_THREAD_ATTRIBUTE = "CHAT_THREAD"
export const MESSAGE_ATTRIBUTE = "CHAT_MESSAGE"
export const CHAT_UTILITY_ATTRIBUTE = "CHAT_UTILITY"
export const CHAT_CITATION_ATTRIBUTE = "CHAT_CITATION"
export const DEFAULT_MONTHS_AGO = 3
export const DEFAULT_DAYS_AGO = 7
