import { FC, memo } from "react";
import { Prism } from "react-syntax-highlighter";
import { atomDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import { ClipboardIcon } from "lucide-react";
import { Button } from "../ui/button";


export const fence = {
  render: "CodeBlock",
  attributes: {
    language: {
      type: String,
    },
    value: {
      type: String,
    },
  },
};

interface Props {
  language: string;
  children: string;
}

export const CodeBlock: FC<Props> = memo(({ language, children }) => {
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(children + "\n\nCode generated by QChat");
    } catch (err) {
      console.error('Failed to copy code:', err);
    }
  };

  return (
    <div className="relative group">
      <Prism language={language} style={atomDark} PreTag="pre">
        {children}
      </Prism>
      <Button onClick={handleCopy} className="absolute top-2 right-2 focus:bg-accent" title="Copy code">
        <ClipboardIcon />
        Copy code
      </Button>
    </div>
  );
});

CodeBlock.displayName = "CodeBlock";


