name: "🛠️ - Build Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 📦 - Install dependencies
        run: npm ci
        working-directory: src

      - name: 🕵️‍♂️ - Run linting
        run: npm run lint
        working-directory: src

      - name: 🛠️ - Run build
        run: npm run build
        working-directory: src
